### ISSUE TITLE
Any way to scroll left based on time

### ISSUE THREAD

**Issue by vijeeshin** [xzdarcy/react-timeline-editor#12]
Any way to scroll left based on time, i have only time parameter, right now i think its based on px

**Comment by xzdarcy** [comment]
> Any way to scroll left based on time, i have only time parameter, right now i think its based on px

You can convert time to px by the `scale`,`scaleWidth`, `startLeft` parameters.  
First, pass these parameters to the timeline.
```
<Timeline
        ...
        scale={scale}
        scaleWidth={scaleWidth}
        startLeft={startLeft}
/>
```
Then calculate the scroll left.
```
// where to start auto scrolling, you can customize according to the timeline panel length.
const autoScrollFrom = 500;
// scroll left
const left = time * (scaleWidth / scale) + startLeft - autoScrollFrom;
// set scroll left
timelineState.current.setScrollLeft(left)
```

**Comment by xzdarcy** [comment]
More info about `scale`,`scaleWidth`, `startLeft` you can see [docs](https://zdarcy.com/editor-demo/editor-scale-customization).

**Comment by vijeeshin** [comment]
Thanks it worked like charm
