### ISSUE TITLE
在使用的过程中发现功能有缺失

### ISSUE THREAD

**Issue by wuchang6** [xzdarcy/react-timeline-editor#13]
我在使用的过程中发现左右bound无法判断向哪个方向移动，不能更精确的限制bounds的移动
想和您聊聊关于这个的问题

**Comment by xzdarcy** [comment]
没太理解，可以详细描述下么？

**Comment by wuchang6** [comment]
比如我想在不影响时间线移动的情况下去限制它的长度不能超出一个固定值，这个就无法实现

**Comment by wuchang6** [comment]
我这边是刚刚实习的小白，读了两天您的源码了，这个问题实在是解决不了

**Comment by wuchang6** [comment]
我这边呢有个初步的想法，就是给bounds再去添加一个拖拽方向的属性

**Comment by xzdarcy** [comment]
还是太get到您这边的需求，bounds是指每个动作块的移动限制区域么？是否是这个需求呢？
![image](https://user-images.githubusercontent.com/43289714/206353032-ec2f7e0c-9996-44d9-8393-bb2724881eb6.png)

**Comment by xzdarcy** [comment]
可以尝试这两个api，返回false会阻止resize。这里提供了一系列api用来让用户自定义扩展需求
![image](https://user-images.githubusercontent.com/43289714/206354028-0cba134c-484d-4a48-99ed-8e3d3f12ca5d.png)

**Comment by xzdarcy** [comment]
> 不是的，这个太局限了，就是我现在正在做一款视频编辑工具，时间线是视频的缩略图，我对这个时间线去操作，前提是这个时间线可以随意的左右移动，但是呢，我又想让它的总时长不能超过原视频的时长，这个需求可以参考[https://www.veed.io/这个网站](https://www.veed.io/%E8%BF%99%E4%B8%AA%E7%BD%91%E7%AB%99)
另外提一下～这个时间轴组件目前只适配pc端哈～不支持移动端

**Comment by wuchang6** [comment]
感谢感谢，这边的确是解决不了，我还要想一些别的办法
