### ISSUE TITLE
轨道间的块，可以上下移动

### ISSUE THREAD

**Issue by juntaosun** [xzdarcy/react-timeline-editor#14]
比如有轨道A和轨道B：
希望：轨道A中的剪辑块，可以任意拖到轨道B中。

拖放前：
轨道A----------{a1}-------------
轨道B---{b1}-------------{b2}---

拖放后：
轨道A-------------------------------
轨道B---{b1}---{a1}----------{b2}---

因为在常规编辑操作中，相同类型的轨道中的数据块，应该可以（交换，插入，分离）
参考《剪映》软件的轨道编辑
https://www.capcut.cn/

**Comment by xzdarcy** [comment]
与 #5 这个重复了，先关了。不过目前工作比较忙，这个功能改动比较大需要的测试比较多，近期可能没有时间增加该功能，后续空闲下来会来补充这个能力。
