### ISSUE TITLE
Callback for cursor time being set by clicking (not dragging)

### ISSUE THREAD

**Issue by rewbs** [xzdarcy/react-timeline-editor#22]
Hi, thanks for the great work.

I need my UI to react to the cursor changing position. The onCursorDrag callback works for most cases, but users can also click on the timeline (without dragging) to set the cursor time. As far as I can tell there's no hook for this event that includes the cursor time in the event object. Could we possibly get one? Thanks!

**Comment by ShahriarDhruvo** [comment]
What are you saying! You don't need any hook for that as it works right out of the box. When you click on the header section of the timeline then the cursor will move to that point.
![image](https://user-images.githubusercontent.com/42747800/219800373-4af9c644-6dee-48dc-8522-b1918a98a06f.png)
By header section I was taking about this portion of the timeline

**Comment by rewbs** [comment]
Yes it moves the cursor. But if I have an external component that reacts to the cursor position, I need to update it with the new cursor position. Currently I can only get the cursor position via a callback when the cursor is dragged, not when it is clicked.

**Comment by reactone** [comment]
It’s definitely possible as I have this functionality implemented.

**Comment by rewbs** [comment]
> It’s definitely possible as I have this functionality implemented.

Great! Which callback are you using to get the cursor position when the header is clicked?

**Comment by xzdarcy** [comment]
I have just added `onClickTimeArea` api, you can try this version [v0.1.8](https://github.com/xzdarcy/react-timeline-editor/releases/tag/v0.1.8)

**Comment by rewbs** [comment]
> I have just added `onClickTimeArea` api, you can try this version [v0.1.8](https://github.com/xzdarcy/react-timeline-editor/releases/tag/v0.1.8)

Thanks, that works perfectly.

**Comment by ShahriarDhruvo** [comment]
Also can you make the onClickTimeArea to take void too? Or am I doing something wrong!

![image](https://user-images.githubusercontent.com/42747800/220110733-9c612afd-a501-43bb-81e7-f30226a046b1.png)
