### ISSUE TITLE
Cannot read properties of undefined (reading 'getBoundingClientRect')

### ISSUE THREAD

**Issue by ShahriarDhruvo** [xzdarcy/react-timeline-editor#23]
Let's say I have implemented this whole timeline in page 1 and then switch to any other page from there then it gives me this error in NextJS 13.

Basically if you switch page in nextjs then you will get this type error

![image](https://user-images.githubusercontent.com/42747800/219786283-aa21a495-1e19-41d5-a9b0-74007b455957.png)

**Comment by ShahriarDhruvo** [comment]
Maybe this can help you @xzdarcy?

https://stackoverflow.com/questions/65678540/react-typeerror-cannot-read-property-getboundingclientrect-of-undefined

**Comment by xzdarcy** [comment]
Thanks! I just fixed this issue and released this version [v0.1.8](https://github.com/xzdarcy/react-timeline-editor/releases/tag/v0.1.8).

**Comment by ShahriarDhruvo** [comment]
Thanks it has been fixed. You can close this issue.
