### ISSUE TITLE
How to restrict maximum cursor movement?

### ISSUE THREAD

**Issue by ShahriarDhruvo** [xzdarcy/react-timeline-editor#27]
As far as I can tell there is no feature right now which restrict the cursor not to move beyond some point. Like if I do not want my cursor to move beyond 1 minute mark I cannot do that. You can restrict the action's maximum movement by setting `maxEnd` value. But there is nothing like this for the cursor. Basically what I want that my cursor shouldn't move after the scale has finished. As you can see I set the `maxScaleCount` to 2m so I want the cursor also not to move beyond that 2m mark but I cannot find anything that do so 😞 Also that 2m text has been chopped out for the reason explained in #26 😅
![image](https://user-images.githubusercontent.com/42747800/220133108-f7ba01c0-72de-4367-9367-a7dae0a4ef16.png)

**Comment by ShahriarDhruvo** [comment]
@xzdarcy can you mention me a workaround for this?

**Comment by xzdarcy** [comment]
Sorry for being busy with work recently, I will deal with it as soon as possible and let you know

**Comment by xzdarcy** [comment]
> @xzdarcy can you mention me a workaround for this?

I have fixed this, you can try v0.1.9.

**Comment by ShahriarDhruvo** [comment]
What props do I need to pass?

**Comment by ShahriarDhruvo** [comment]
What props do I need to pass?

**Comment by ShahriarDhruvo** [comment]
Thanks you can close this one :3
