### ISSUE TITLE
How to scroll timeline without resizing action

### ISSUE THREAD

**Issue by ftirej** [xzdarcy/react-timeline-editor#3]
Hi, is there a way to move the timeline while dragging the cursor?. The only way i found is to resize the action.

**Comment by xzdarcy** [comment]
I'm so sorry I didn't consider this feature before. I just added this capability and released an alpha version`0.1.3-alpha.1`. You can try it out if it meets your needs. Just set `autoScroll` to `true`.
```
 <Timeline 
     ...
     autoScroll={true}
  />
```
