### ISSUE TITLE
Events when cursor drag start and cursor drag stop

### ISSUE THREAD

**Issue by ftirej** [xzdarcy/react-timeline-editor#4]
Hi im using the timeline as a player timeline for video. Im setting the time from the timestamp of the video. Can you add a drag start and drag stop to get the time from the timeline and set the video time?. This way i can stop setting the time of the timeline from the video while is im dragging the cursor. By the way! great job! and thanks for the hard work.

**Comment by xzdarcy** [comment]
I added the following two parameters and released the test version 0.1.4-alpha.0. You can try if it meets your needs
![image](https://user-images.githubusercontent.com/43289714/182034598-9f0c8e59-4643-4df1-9cda-85f0d7f95d3b.png)

**Comment by ftirej** [comment]
Hi, it worked like a charm. Maybe this events could also be added to the TimelineState so we can listen to the start and end. This way you can set different events to the video player, like set the current position of the video.

**Comment by xzdarcy** [comment]
> Hi, it worked like a charm. Maybe this events could also be added to the TimelineState so we can listen to the start and end. This way you can set different events to the video player, like set the current position of the video.

Hi, are you meaning for the engine event? The events of the engine have been exposed through TimelineState (In my design, TimelineState is used to expose some APIs of the built-in engine). You can get more engine event information from the [link](https://zdarcy.com/engine/api#listener).
```
  timelineState.listener.on('afterSetTime', () => {
    ...
  })
```
