### ISSUE TITLE
onChange error

### ISSUE THREAD

**Issue by chaeyan** [xzdarcy/react-timeline-editor#41]
<img width="839" alt="Screenshot 2023-12-16 09 13 48" src="https://github.com/xzdarcy/react-timeline-editor/assets/32681723/c860ba16-6c80-461b-9fed-0c852d6ec33c">

react 18 and typescript 5.3.3

this occurs when you try to drag an item in the timeline to change its start position

**Comment by zane-programs** [comment]
Did you include an `onChange` prop in your `Timeline` component? The same happened to me when I first integrated the component into my project, as I didn't know about this prop yet.

**Comment by chaeyan** [comment]
Yeah I figured it out right after this, it wasnt documented so I had no idea. Someone needs to re-do the whole docs in English.. its a mess and you find out features yourself

**Comment by zane-programs** [comment]
Yeah, would be great to have English-language docs. I don't speak any Chinese, but I was able to translate the site via my browser to understand what I needed to do.

Separately, it might be nice to have some way for the editor to fail gracefully if an `onChange` prop is not supplied by the client. Possibly a warning in console and leave it at that? I'll think and make a PR. :)
