### ISSUE TITLE
import { bpfrpt_proptype_WindowScroller } from "../WindowScroller.js";

### ISSUE THREAD

**Issue by havingfu** [xzdarcy/react-timeline-editor#57]
first of all cool library!

When running example code using Vite:
https://github.com/xzdarcy/react-timeline-editor?tab=readme-ov-file#getting-started

I install the package using npm, create the TimelineEditor component using the example, but I get this Error

```
21:28:02 [vite] page reload src/App.jsx
X [ERROR] No matching export in "node_modules/react-virtualized/dist/es/WindowScroller/WindowScroller.js" for import "bpfrpt_proptype_WindowScroller"

    node_modules/react-virtualized/dist/es/WindowScroller/utils/onScroll.js:74:9:
      74 │ import { bpfrpt_proptype_WindowScroller } from "../WindowScroller.js";
```

Can someone help?
Thanks!

**Comment by arthur19312** [comment]
same +1

**Comment by arthur19312** [comment]
related: [https://github.com/bvaughn/react-virtualized/issues/1849](https://github.com/bvaughn/react-virtualized/issues/1849)

**Comment by arthur19312** [comment]
> related: [bvaughn/react-virtualized#1849](https://github.com/bvaughn/react-virtualized/issues/1849)

It works, use [patch-package](https://github.com/ds300/patch-package) or just `pnpm patch`.
