### ISSUE TITLE
Too many rows and vertical scroll

### ISSUE THREAD

**Issue by dieZwergin** [xzdarcy/react-timeline-editor#60]
The timeline always has one more row than my data. How can I fix this? I only noticed it when I added a bottom border to my rows.
![image](https://github.com/user-attachments/assets/8faab632-4795-40d5-b927-92574999954f)

And the horizontal scrollbar always causes the Timeline so have a small vertical scroll upon entering the timeline with the cursor. This problem also appears in all demos from the documentation. Is there a fix for this?

**Comment by theLeon33** [comment]
lol,  horizontal scrollbar was vitual, not a DOM provided custom styles, so that it won't be modified unless fork the repo.
another question, check ur `editorData` props which coded base on React useState, async render

**Comment by dieZwergin** [comment]
The scrollbar problem seems to stem from the React Virtualized library. Found a workaround which is fine for my purpose by hiding the overflow-y of 'ReactVirtualized__Grid' within timeline-editor-edit-area.
