### ISSUE TITLE
Timeline not scrolling to right based on time

### ISSUE THREAD

**Issue by vijeeshin** [xzdarcy/react-timeline-editor#9]
First of all, Great work. Hi, I am using React Player as my video source, based on the lib, I am setting the timeline time from the react player output. My auto scroll prop of react-timeline-editor is true, but the timeline not scrolling to the right with respect to the time from the video. Please help.

**Comment by xzdarcy** [comment]
> First of all, Great work. Hi, I am using React Player as my video source, based on the lib, I am setting the timeline time from the react player output. My auto scroll prop of react-timeline-editor is true, but the timeline not scrolling to the right with respect to the time from the video. Please help.

AutoScroll is used for scrolling while dragging. Scrolling by time when playing is another set of logic.
Therefore, added `TimelineState.setScrollLeft` attribute, allow custom scrollLeft on demand.
Released version 0.0.5.
You can refer to this example：[demo](https://zdarcy.com/engine#%E7%BC%96%E8%BE%91%E6%97%B6%E8%BF%90%E8%A1%8C)

**Comment by vijeeshin** [comment]
@xzdarcy Thanks i will try

**Comment by vijeeshin** [comment]
work like a charm, Thank you for your effort
